name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci/tox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Run CI with tox
      run: |
        pip install tox
        tox
